version: '3'
services:
  wordpress:
    depends_on:
      - mariadb
    image: wordpress:php8.2
    volumes:
      - ./wp-content/:/var/www/html/wp-content/
      - .htaccess:/var/www/html/.htaccess
      - ./wp-cli.phar:/usr/local/bin/wp
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: ${DEV_DB_NAME}
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: ${DEV_DB_PASS}
      WORDPRESS_TABLE_PREFIX: ${DEV_TABLE_PREFIX}
      WORDPRESS_DEBUG: ${WP_DEBUG}
      WORDPRESS_CONFIG_EXTRA: |
        /* Extra config */
        define('WP_HOME', '${DEV_HOST}' );
        define('WP_SITEURL', WP_HOME );
        define('WP_ENV', '${WP_ENV}' );
        define('WP_MEMORY_LIMIT', '${WP_MEMORY_LIMIT}' );
        define('DISABLE_WP_CRON', true);
        define('RECOVERY_MODE_EMAIL', '${WP_DEV_EMAIL}' );
    ports:
      - ${HTTP_PORT}:80
    networks:
      - back
  mariadb:
     image: mariadb:lts
     volumes:
       - db_data:/var/lib/mysql
     environment:
       MYSQL_ROOT_PASSWORD: ${DEV_DB_PASS}
       MYSQL_DATABASE: ${DEV_DB_NAME}
       MARIADB_AUTO_UPGRADE: 1
     networks:
       - back
     ports:
       - ${DB_PORT}:3306
networks:
  back:
volumes:
  db_data:
